---
provisioner:
  name: chef_zero

driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 3096
    cpuexecutioncap: 50

platforms:
  # Opscode vagrant box names taken from http://www.vagrantbox.es/
  - name: centos-6.5
    run_list:
      - recipe[java]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: /etc/httpd/conf/httpd.conf
            init_script_path: /etc/init.d/httpd
      java:
        jdk_version: 7

  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7

  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7

  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: apache_wsagent
    run_list:
      - recipe[apache2]
      - recipe[dynatrace::apache_wsagent]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            do_patch_init_script: true
        wsagent_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-wsagent.tar
    includes:
      - centos-6.5
      - debian-7.4
      - ubuntu-12.04

  - name: agents_package
    run_list:
      - recipe[dynatrace::agents_package]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-unix.jar
#          windows:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-x86.msi

  - name: agents_package_uninstall
    run_list:
      - recipe[dynatrace::agents_package]
      - recipe[dynatrace::agents_package_uninstall]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-unix.jar
    excludes:
      - windows-2012r2

  - name: collector
    run_list:
      - recipe[dynatrace::collector]
    attributes:
      dynatrace:
        collector:
          jvm:
            xms: 256M
            xmx: 1024M
            perm_size: 256m
            max_perm_size: 384m
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-collector.jar
    excludes:
      - windows-2012r2

  - name: collector_uninstall
    run_list:
      - recipe[dynatrace::collector]
      - recipe[dynatrace::collector_uninstall]
    attributes:
      dynatrace:
        collector:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-collector-linux-x86.jar
    excludes:
      - windows-2012r2

  - name: dotnet_agent
    run_list:
      - recipe[dynatrace::dotnet_agent]
    attributes:
      dynatrace:
#        agents_package:
#          windows:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-x86.msi
        dotnet_agent:
          process_list: [w3wp.exe -ap myApp]
    includes:
      - windows-2012r2

  - name: dynatrace_user
    run_list:
      - recipe[dynatrace::dynatrace_user]

  - name: dynatrace_user_uninstall
    run_list:
      - recipe[dynatrace::dynatrace_user]
      - recipe[dynatrace::dynatrace_user_uninstall]

  - name: host_agent
    run_list:
      - recipe[dynatrace::host_agent]
    attributes:
      dynatrace:
        host_agent:
          host_agent_name:
            myhostagent
          collector:
            myhostaddr
#          installer:
#            file_url: http://172.18.129.150:8000/dynatrace-hostagent-linux-x86-64.tar

  - name: host_agent_uninstall
    run_list:
      - recipe[dynatrace::host_agent]
      - recipe[dynatrace::host_agent_uninstall]
#    attributes:
#      dynatrace:
#        host_agent:
#          installer:
#            file_url: http://172.18.129.150:8000/dynatrace-hostagent-linux-x86-64.tar

  - name: java_agent
    run_list:
      - recipe[dynatrace::agents_package]
      - recipe[dynatrace::java_agent]
    attributes:
      dynatrace:
        agents_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-agent.jar
        java_agent:
          env_var:
            file_name: /tmp/environment
    includes:
      - centos-6.5
      - debian-7.4
      - ubuntu-12.04

  - name: server
    run_list:
      - recipe[dynatrace::server]
    attributes:
      dynatrace:
        server:
          do_pwh_connection: true
          externalhostname: "myaddr"
          sizing: small
#          collector_port: 6699 # on version 6.5
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-server-linux-x86-64.jar
    excludes:
          - windows-2012r2

  - name: server_uninstall
    run_list:
      - recipe[dynatrace::server]
      - recipe[dynatrace::server_uninstall]
#    attributes:
#      dynatrace:
#        server:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-server-linux-x86-64.jar
    excludes:
          - windows-2012r2

  - name: wsagent_package
    run_list:
      - recipe[dynatrace::wsagent_package]
    attributes:
      dynatrace:
        wsagent_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-wsagent.tar
          windows:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-agents.msi