---
provisioner:
  name: chef_zero

driver:
  name: docker
  # In case of error "Message: You must first install the Docker CLI tool" try uncommenting following line
#  use_sudo: false

# NOTE: To speed up test kitchen execution time:
# * Run the docker_images/build_images.sh script
# * Uncomment "image: ..." lines in the 'platforms' section
# * Setup a cache server with Dynatrace installers downloaded locally using for example python e.g. python -m SimpleHTTPServer 8000
# * Uncomment and update the file_url attributes in the 'suites' section

platforms:
  - name: centos-6
    driver_config:
#      image: centos-6-chef
      provision_command:
        - yum update -y
        - yum install -y net-tools tar
    run_list:
      - recipe[java]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: /etc/httpd/conf/httpd.conf
            init_script_path: /etc/init.d/httpd
      java:
        jdk_version: 7

  - name: debian-7.8
    driver_config:
#      image: debian-7.8-chef
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar
        # See https://github.com/docker/docker/issues/963
        - apt-get install -y --no-install-recommends openjdk-7-jdk
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: '/etc/apache2/apache2.conf'
          linux:
            apache_daemon: 'apache2'

  - name: ubuntu-12.04
    driver_config:
#      image: ubuntu-12.04-chef
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: '/etc/apache2/apache2.conf'
          linux:
            apache_daemon: 'apache2'

suites:
  - name: apache_wsagent
    run_list:
      - recipe[apache2]
      - recipe[dynatrace::apache_wsagent]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            do_patch_init_script: true
        wsagent_package:
          linux:
            installer:
              file_url:  http://172.18.129.150:8000/dynatrace-wsagent-linux-x86-64.tar

  - name: agents_package
    run_list:
      - recipe[dynatrace::agents_package]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-unix.jar

  - name: agents_package_uninstall
    run_list:
      - recipe[dynatrace::agents_package]
      - recipe[dynatrace::agents_package_uninstall]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-unix.jar

  - name: collector
    run_list:
      - recipe[dynatrace::collector]
    attributes:
      dynatrace:
        collector:
          jvm:
            xms: 256M
            xmx: 1024M
            perm_size: 256m
            max_perm_size: 384m
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-collector-linux-x86.jar

  - name: collector_uninstall
    run_list:
      - recipe[dynatrace::collector]
      - recipe[dynatrace::collector_uninstall]
#    attributes:
#      dynatrace:
#        collector:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-collector-linux-x86.jar

  - name: agents_package
    run_list:
      - recipe[dynatrace::agents_package]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-agent-unix.jar

  - name: memory_analysis_server
    run_list:
      - recipe[dynatrace::memory_analysis_server]
    attributes:
      dynatrace:
        memory_analysis_server:
          jvm:
            xms: 256M
            xmx: 1024M
            perm_size: 256m
            max_perm_size: 384m
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-analysisserver-linux-x86.jar

  - name: server
    run_list:
      - recipe[dynatrace::server]
    attributes:
      dynatrace:
        server:
          do_pwh_connection: true
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-server-linux-x86.jar
          sizing: small

  - name: wsagent_package
    run_list:
      - recipe[dynatrace::wsagent_package]
#    attributes:
#      dynatrace:
#        wsagent_package:
#          linux:
#            installer:
#              file_url: http://172.18.129.150:8000/dynatrace-wsagent-linux-x64.tar
