---
provisioner:
  name: chef_zero

driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 3096
    cpuexecutioncap: 50

platforms:
  # Opscode vagrant box names taken from http://www.vagrantbox.es/
  - name: centos-6.5
    run_list:
      - recipe[java]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: /etc/httpd/conf/httpd.conf
            init_script_path: /etc/init.d/httpd
      java:
        jdk_version: 7
      postgresql:
        enable_pgdg_yum: true
        version: '9.2'
        client:
          packages: ['postgresql92-devel']
        server:
          packages: ['postgresql92-server']
        contrib:
          packages: ['postgresql92-contrib']

  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7
      postgresql:
        enable_pgdg_apt: true
        version: '9.2'
        server:
          packages: ['postgresql-9.2']
        client:
          packages: ['postgresql-client-9.2', 'libpq-dev']
        contrib:
          packages: ['postgresql-contrib-9.2']

  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7
      postgresql:
        enable_pgdg_apt: true
        version: '9.2'
        server:
          packages: ['postgresql-9.2']
        client:
          packages: ['postgresql-client-9.2', 'libpq-dev']
        contrib:
          packages: ['postgresql-contrib-9.2']

suites:
  - name: apache_wsagent
    run_list:
      - recipe[apache2]
      - recipe[dynatrace::apache_wsagent]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            do_patch_init_script: true
        wsagent_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/dynatrace-wsagent.tar
    includes:
      - centos-6.5
      - debian-7.4
      - ubuntu-12.04

  - name: agents_package
    run_list:
      - recipe[dynatrace::agents_package]
    attributes:
      dynatrace:
        agents_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/dynatrace-agents.jar

  - name: collector
    run_list:
      - recipe[dynatrace::collector]
    attributes:
      dynatrace:
        collector:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/dynatrace-collector.jar

  - name: java_agent
    run_list:
      - recipe[dynatrace::agents_package]
      - recipe[dynatrace::java_agent]
    attributes:
      dynatrace:
        agents_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/dynatrace-agents.jar
        java_agent:
          env_var:
            file_name: /tmp/environment

  - name: server
    run_list:
      - recipe[dynatrace_pwh_postgresql]
      - recipe[dynatrace::server]
    attributes:
      dynatrace:
        server:
          do_pwh_connection: true
          license:
            file_url: http://10.0.2.2/dynatrace/dynatrace-license.key
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/dynatrace.jar
    includes:
      - centos-6.5
      - debian-7.4
      - ubuntu-12.04

  - name: wsagent_package
    run_list:
      - recipe[dynatrace::wsagent_package]
    attributes:
      dynatrace:
        wsagent_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/dynatrace-wsagent.tar
