---
provisioner:
  name: chef_zero

driver:
  name: docker

platforms:
  - name: centos-6
    driver_config:
      provision_command:
        - yum update -y
        - yum install -y net-tools tar
    run_list:
      - recipe[java]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: /etc/httpd/conf/httpd.conf
            init_script_path: /etc/init.d/httpd
      java:
        jdk_version: 7

  - name: debian-7.8
    driver_config:
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7

  - name: ubuntu-12.04
    driver_config:
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7

suites:
  - name: apache_wsagent
    run_list:
      - recipe[apache2]
      - recipe[dynatrace::apache_wsagent]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            do_patch_init_script: true
        wsagent_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-wsagent.tar

  - name: agents_package
    run_list:
      - recipe[dynatrace::agents_package]
    attributes:
      dynatrace:
        agents_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-agent.jar

  - name: collector
    run_list:
      - recipe[dynatrace::collector]
    attributes:
      dynatrace:
        collector:
          jvm:
            xms: 256M
            xmx: 1024M
            perm_size: 256m
            max_perm_size: 384m
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-collector.jar

  - name: java_agent
    run_list:
      - recipe[dynatrace::agents_package]
      - recipe[dynatrace::java_agent]
    attributes:
      dynatrace:
        agents_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-agent.jar
        java_agent:
          env_var:
            file_name: /tmp/environment

  - name: memory_analysis_server
    run_list:
      - recipe[dynatrace::memory_analysis_server]
    attributes:
      dynatrace:
        memory_analysis_server:
          jvm:
            xms: 256M
            xmx: 1024M
            perm_size: 256m
            max_perm_size: 384m
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-analysisserver.jar

  - name: server
    run_list:
      - recipe[dynatrace::server]
    attributes:
      dynatrace:
        server:
          do_pwh_connection: true
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-server.jar
          sizing: small

  - name: wsagent_package
    run_list:
      - recipe[dynatrace::wsagent_package]
    attributes:
      dynatrace:
        wsagent_package:
          linux:
            installer:
              file_url: http://10.0.2.2/dynatrace/6.3/dynatrace-wsagent.tar