---
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 3096
    cpuexecutioncap: 50

platforms:
  # Opscode vagrant box names taken from http://www.vagrantbox.es/
  - name: centos-6.5
    run_list:
      - recipe[java]
    attributes:
      dynatrace:
        apache_wsagent:
          apache:
            config_file_path: /etc/httpd/conf/httpd.conf
            init_script_path: /etc/init.d/httpd

  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[java]

  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[java]

  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: apache_wsagent
    run_list:
      - recipe[apache2]
      - recipe[dynatrace::apache_wsagent]
    attributes:
      dynatrace:
        apache_wsagent:
          linux:
            # WORKAROUND: see description of apache_daemon attribute in dynatrace cookbook.
            apache_daemon: ''
#        wsagent_package:
#          linux:
#            installer:
#              file_url:  http://192.168.1.2:8000/dynatrace-wsagent-linux-x86-64.tar
    excludes:
      - windows-2012r2

  - name: apache_wsagent_uninstall
    run_list:
      - recipe[apache2]
      - recipe[dynatrace::apache_wsagent]
      - recipe[dynatrace::apache_wsagent_uninstall]
    attributes:
      dynatrace:
        apache_wsagent:
          linux:
            # WORKAROUND: see description of apache_daemon attribute in dynatrace cookbook.
            apache_daemon: ''
#        wsagent_package:
#          linux:
#            installer:
#              file_url:  http://192.168.1.2:8000/dynatrace-wsagent-linux-x86-64.tar
    excludes:
      - windows-2012r2

  - name: agents_package
    run_list:
      - recipe[dynatrace::agents_package]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-unix.jar
#          windows:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-x86.msi

  - name: agents_package_uninstall
    run_list:
      - recipe[dynatrace::agents_package]
      - recipe[dynatrace::agents_package_uninstall]
#    attributes:
#      dynatrace:
#        agents_package:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-unix.jar
    excludes:
      - windows-2012r2

  - name: one_agent
    run_list:
      - recipe[dynatrace::one_agent]
#    attributes:
#      dynatrace:
#        one_agent:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-one-agent-linux-x86.tgz
#          windows:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-one-agent-x86.msi

  - name: collector
    run_list:
      - recipe[dynatrace::collector]
    attributes:
      dynatrace:
        collector:
          jvm:
            xms: 256M
            xmx: 1024M
            perm_size: 256m
            max_perm_size: 384m
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-collector.jar
    excludes:
      - windows-2012r2

  - name: collector_uninstall
    run_list:
      - recipe[dynatrace::collector]
      - recipe[dynatrace::collector_uninstall]
    attributes:
      dynatrace:
        collector:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-collector-linux-x86.jar
    excludes:
      - windows-2012r2

  - name: dotnet_agent
    run_list:
      - recipe[dynatrace::dotnet_agent]
    attributes:
      dynatrace:
#        agents_package:
#          windows:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-x86.msi
        dotnet_agent:
          process_list: [w3wp.exe -ap myApp]
    includes:
      - windows-2012r2

  - name: dynatrace_user
    run_list:
      - recipe[dynatrace::dynatrace_user]

  - name: dynatrace_user_uninstall
    run_list:
      - recipe[dynatrace::dynatrace_user]
      - recipe[dynatrace::dynatrace_user_uninstall]

  - name: host_agent
    run_list:
      - recipe[dynatrace::host_agent]
    attributes:
      dynatrace:
        host_agent:
          host_agent_name:
            myhostagent
          collector:
            myhostaddr
#          installer:
#            file_url: http://192.168.1.2:8000/dynatrace-hostagent-linux-x86-64.tar

  - name: host_agent_uninstall
    run_list:
      - recipe[dynatrace::host_agent]
      - recipe[dynatrace::host_agent_uninstall]
#    attributes:
#      dynatrace:
#        host_agent:
#          installer:
#            file_url: http://192.168.1.2:8000/dynatrace-hostagent-linux-x86-64.tar

  - name: iis_wsagent
    run_list:
      - recipe[dynatrace::iis_wsagent]
#    attributes:
#      dynatrace:
#        wsagent_package:
#          windows:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-x86.msi
    includes:
      - windows-2012r2

  - name: java_agent
    run_list:
      - recipe[dynatrace::java_agent]
    attributes:
      dynatrace:
        java_agent:
          env_var:
            file_name: /tmp/environment
#        agents_package:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-unix.jar
    excludes:
      - windows-2012r2

  - name: server
    run_list:
      - recipe[dynatrace::server]
    attributes:
      dynatrace:
        server:
          pwh_connection:
            # Allow error 500 (connection failed) to pass our test
            success_codes: ['200', '500']
          sizing: small
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-server-linux-x86-64.jar
    excludes:
      - windows-2012r2

  - name: server_uninstall
    run_list:
      - recipe[dynatrace::server]
      - recipe[dynatrace::server_uninstall]
#    attributes:
#      dynatrace:
#        server:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-server-linux-x86.jar
    excludes:
      - windows-2012r2

  - name: server_update
    run_list:
      - recipe[dynatrace::server]
      - recipe[dynatrace::server_update]
    attributes:
      dynatrace:
        server:
          collector_port: 6698 # on version 6.3 (default is 6699 on version 6.5)
          linux:
            # TODO: currently no update available on version 6.5 thus testing version 6.3
            installer:
              file_url: http://downloads.dynatracesaas.com/6.3/dynatrace-server-linux-x86.jar
            update:
              file_url: https://files.dynatrace.com/downloads/fixpacks/dynaTrace-6.3.10.1010.zip
#            update:
#              update_file_url: http://192.168.1.2:8000/dynaTrace-6.3.10.1010.zip
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-server-linux-x86-64.jar
    excludes:
      - windows-2012r2

  - name: wsagent_package
    run_list:
      - recipe[dynatrace::wsagent_package]
#    attributes:
#      dynatrace:
#        wsagent_package:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-wsagent-linux-x86-64.tar
#          windows:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-agent-x86.msi

  - name: wsagent_package_uninstall
    run_list:
      - recipe[dynatrace::wsagent_package]
      - recipe[dynatrace::wsagent_package_uninstall]
#    attributes:
#      dynatrace:
#        wsagent_package:
#          linux:
#            installer:
#              file_url: http://192.168.1.2:8000/dynatrace-wsagent-linux-x86-64.tar
    excludes:
      - windows-2012r2